from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework import status

# Add this new endpoint to accounts/views.py
from django.db import IntegrityError

@api_view(['POST'])
@permission_classes([AllowAny])  # Anyone can access the registration page
def signup_view(request):
    username = request.data.get('username')
    password = request.data.get('password')
    confirm_password = request.data.get('confirm_password')

    # 1. Basic Validation
    if not username or not password:
        return Response({"error": "Username and password cannot be empty, bro."}, status=status.HTTP_400_BAD_REQUEST)
    
    if password != confirm_password:
        return Response({"error": "Passwords do not match!"}, status=status.HTTP_400_BAD_REQUEST)

    if len(password) < 6:
        return Response({"error": "Password must be at least 6 characters long."}, status=status.HTTP_400_BAD_REQUEST)

    # 2. Check if username exists
    if User.objects.filter(username=username).exists():
        return Response({"error": "This username is already taken. Try another one!"}, status=status.HTTP_400_BAD_REQUEST)

    # 3. Create user securely
    try:
        # CRITICAL: Use create_user, NOT create(). create_user hashes the password!
        user = User.objects.create_user(username=username, password=password)
        
        # Smooth UX: Auto-login the user immediately after signing up
        login(request, user)
        
        return Response({"message": "User registered successfully!", "username": user.username}, status=status.HTTP_201_CREATED)
    except Exception as e:
        return Response({"error": f"Database insertion failed: {e}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


# View to render the static HTML signup template page
def signup_page_view(request):
    return render(request, 'accounts/signup.html')

@api_view(['POST'])
@permission_classes([AllowAny])  # Anyone should be able to reach the login screen
def login_view(request):
    username = request.data.get('username')
    password = request.data.get('password')

    if not username or not password:
        return Response({"error": "Please provide both username and password"}, status=status.HTTP_400_BAD_REQUEST)

    user = authenticate(request, username=username, password=password)
    
    if user is not None:
        login(request, user)  # This hooks into Django's session framework and sends a session cookie
        return Response({"message": "Login successful", "username": user.username}, status=status.HTTP_200_OK)
    
    return Response({"error": "Invalid username or password, bro."}, status=status.HTTP_401_UNAUTHORIZED)


@api_view(['POST'])
@permission_classes([IsAuthenticated])  # Only logged-in users can log out
def logout_view(request):
    logout(request)
    return Response({"message": "Successfully logged out"}, status=status.HTTP_200_OK)


def login_page_view(request):
    """
    Renders the static HTML login template interface.
    """
    return render(request, 'accounts/login.html')



@api_view(['GET'])
@permission_classes([IsAuthenticated])
def dynamic_profile_view(request):
    """
    Fetches the profile info and aggregates generation metrics for the authenticated user.
    """
    user = request.user
    
    # Count the total scripts generated by this user using the related_name defined earlier
    total_generations = user.scripts.count()
    
    return Response({
        "username": user.username,
        "email": user.email if user.email else "no-email@creator.com",
        "date_joined": user.date_joined.strftime("%B %d, %Y"),
        "total_generations": total_generations
    }, status=status.HTTP_200_OK)