# Generated by Django 5.2.7 on 2025-10-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_text', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='To keep the sentences in order')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A title for this script', max_length=255)),
                ('full_text', models.TextField(help_text='The complete transcript or text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="'unsplash', 'pexels', 'pixabay', etc.", max_length=50)),
                ('image_url', models.URLField(max_length=1024)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_selected', models.BooleanField(default=False)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='image_fetcher.scene')),
            ],
        ),
        migrations.AddField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='image_fetcher.script'),
        ),
    ]
