# Generated by Django 5.2.7 on 2025-10-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='orientation_preference',
            field=models.CharField(choices=[('all', 'All Orientations'), ('landscape', 'Landscape'), ('portrait', 'Portrait')], default='all', help_text='Image orientation preference for this script', max_length=10),
        ),
    ]
