import uuid
from typing import Dict, List
from sqlalchemy.orm import Session
from fastapi import HTTPException, status

from app.services.providers.asset_search_service import AssetSearchService
from app.repositories.scene_repository import SceneRepository
from app.models.search_job import SearchJob, JobStatus
from app.models.asset import Asset
from app.schemas.search import SearchResponse
from app.schemas.provider import ProviderAsset
from app.schemas.ai import SceneAnalysis

class SearchService:
    def __init__(self, db: Session):
        self.db = db
        self.scene_repo = SceneRepository(db)
        self.provider_service = AssetSearchService()

    async def search_assets_for_scene(
        self, 
        scene_id: uuid.UUID, 
        query: str, 
        orientation: str = "all", 
        limit: int = 20, 
        user_id: uuid.UUID = None
    ) -> SearchResponse:
        """
        Executes a multi-provider search for a scene and persists the results.
        """
        # 1. Validate scene
        scene = self.scene_repo.get_by_id(scene_id)
        if not scene:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scene not found")
        
        if scene.script.project.user_id != user_id:
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not authorized to access this scene")

        # 2. Create Search Job (Pending -> Running)
        job = SearchJob(scene_id=scene_id, status=JobStatus.RUNNING)
        self.db.add(job)
        self.db.commit()
        self.db.refresh(job)

        try:
            # 3. Call Providers
            limit_per_provider = max(limit // 3, 5) # Distribute limit roughly
            assets, providers_status = await self.provider_service.search_and_aggregate(
                query=query, 
                orientation=orientation, 
                limit_per_provider=limit_per_provider
            )

            # 4. Persist Candidate Assets
            db_assets = []
            for asset in assets:
                db_assets.append(
                    Asset(
                        search_job_id=job.id,
                        provider_name=asset.provider,
                        provider_asset_id=asset.provider_asset_id,
                        asset_url=asset.image_url,
                        thumbnail_url=asset.thumbnail_url,
                        source_url=asset.source_url,
                        alt_text=asset.alt_text,
                        width=asset.width,
                        height=asset.height,
                        license_type=asset.license
                    )
                )
            self.db.add_all(db_assets)
            
            # 5. Mark Complete
            job.status = JobStatus.COMPLETED
            self.db.commit()

            return SearchResponse(
                scene_id=scene_id,
                query=query,
                providers=providers_status,
                results=assets
            )
        except Exception as e:
            job.status = JobStatus.FAILED
            self.db.commit()
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Search aggregation failed: {str(e)}")

    async def search_scene_assets_from_analysis(
        self,
        scene_id: uuid.UUID,
        analysis: SceneAnalysis,
        user_id: uuid.UUID
    ) -> List[SearchResponse]:
        """
        Executes a search for every visual query generated by Gemini.
        Returns a list of search responses.
        """
        responses = []
        # Fallback if no queries
        queries = analysis.visual_queries if analysis.visual_queries else [analysis.summary]
        
        for query in queries:
            resp = await self.search_assets_for_scene(
                scene_id=scene_id,
                query=query,
                orientation="landscape", # default for storyboard
                limit=15, # 5 per provider
                user_id=user_id
            )
            responses.append(resp)
            
        return responses
