"""add history fields

Revision ID: 167c24464db5
Revises: 2b12a640f53a
Create Date: 2026-08-27 23:27:24.149891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167c24464db5'
down_revision: Union[str, Sequence[str], None] = '2b12a640f53a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('semantic_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('assets', sa.Column('resolution_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('assets', sa.Column('orientation_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('assets', sa.Column('final_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('search_jobs', sa.Column('requested_query', sa.String(), nullable=False, server_default=''))
    op.add_column('search_jobs', sa.Column('ranking_version', sa.String(), nullable=False, server_default='v1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_jobs', 'ranking_version')
    op.drop_column('search_jobs', 'requested_query')
    op.drop_column('assets', 'final_score')
    op.drop_column('assets', 'orientation_score')
    op.drop_column('assets', 'resolution_score')
    op.drop_column('assets', 'semantic_score')
    # ### end Alembic commands ###
