"""add error_message to search_jobs

Revision ID: 2b12a640f53a
Revises: 826ca2a929dc
Create Date: 2026-08-27 03:21:13.490037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b12a640f53a'
down_revision: Union[str, Sequence[str], None] = '826ca2a929dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_jobs', 'error_message')
    # ### end Alembic commands ###
