"""add scene analysis fields

Revision ID: 4ebde5043272
Revises: c5b66d4c718d
Create Date: 2026-09-02 17:04:45.065251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebde5043272'
down_revision: Union[str, Sequence[str], None] = 'c5b66d4c718d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('scenes', sa.Column('analysis', sa.JSON(), nullable=True))
    op.add_column('scenes', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'analyzed_at')
    op.drop_column('scenes', 'analysis')
    op.drop_column('scenes', 'status')
    # ### end Alembic commands ###
