"""add provider fields to asset

Revision ID: 826ca2a929dc
Revises: 183154266bf6
Create Date: 2026-08-27 01:49:55.463933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826ca2a929dc'
down_revision: Union[str, Sequence[str], None] = '183154266bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('provider_asset_id', sa.String(length=255), nullable=False))
    op.add_column('assets', sa.Column('thumbnail_url', sa.String(length=1024), nullable=True))
    op.add_column('assets', sa.Column('source_url', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_assets_provider_asset_id'), 'assets', ['provider_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_provider_asset_id'), table_name='assets')
    op.drop_column('assets', 'source_url')
    op.drop_column('assets', 'thumbnail_url')
    op.drop_column('assets', 'provider_asset_id')
    # ### end Alembic commands ###
