"""add scene title

Revision ID: c5b66d4c718d
Revises: 167c24464db5
Create Date: 2026-08-28 01:27:28.584914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b66d4c718d'
down_revision: Union[str, Sequence[str], None] = '167c24464db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'title')
    # ### end Alembic commands ###
